name: QA Pipeline

on:

  #Ejecucion a demanda
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags de prueba'
        required: true
        default: '@smoke'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalacion de Java 17 y Maven
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Ejecutar pruebas
        run: mvn clean test -Dkarate.tags=${{ inputs.tags }}

      - name: Visualizar reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/karate-reports


    ##PASOS
    #INSTALACION DE JAVA 11,17
    #INSTALACION DE MAVEN
    #CLONAR EL REPOSITORIO

    #EJECUTAR LAS PRUEBAS
    #VISUALIZAR REPORTE


